spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 2000MB
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
    show-sql: true
  datasource: # 배포할때 RDS로 교체하기 위해 지우기
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration:
    accessToken: 10800000
    refreshToken: 1209600000

dify:
  chat:
    secret: ${DIFY_CHAT_KEY}
  knowledge:
    secret: ${DIFY_KNOWLEDGE_KEY}
    id:
      coin: 69ab286f-4ffa-4457-85e6-f109581fa6b3
      stock: 7905b43e-f01b-4da3-86e9-cdb98da174d0
      bonds: 1dd2a824-21b1-43a7-b7d3-f2e5de4e1d52
      estate: 36c321f4-0b2a-411f-b487-a67210e448d5
      futures: 4f5e04ee-9094-424b-8392-2b359541de33
      commodities: 7b15c364-a56a-4ee5-a915-3613059bb7fe
  uri:

naver:
  id: ${NAVER_KEY}
  secret: ${NAVER_SECRET}